const STORE = 'mi-bolsillo-v1';
const defaults = { budget: 0, initialBalance: 0, dollarType: 'blue', dollarRate: null, shortcuts: [
  ['🍽️','Comidas',0],['☕','Café',0],['🚕','Transporte',0],['🛒','Super',0],['🎉','Salida viernes',0],['🏋️','Gimnasio',0],['💊','Salud',0],['🧾','Otro',0]
], movements: [], fixed: [] };
let state = JSON.parse(localStorage.getItem(STORE) || 'null') || structuredClone(defaults);
state = { ...structuredClone(defaults), ...state };
let selectedType = 'expense';
const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n || 0);
const save = () => localStorage.setItem(STORE, JSON.stringify(state));
const today = () => new Date().toISOString().slice(0,10);
const currentMonth = () => new Date().toISOString().slice(0,7);
const formatDate = date => new Date(`${date}T12:00:00`).toLocaleDateString('es-AR',{day:'numeric',month:'short'});
function inThisMonth(m) { return m.date.startsWith(currentMonth()); }
function monthDays() { const d=new Date(); return new Date(d.getFullYear(),d.getMonth()+1,0).getDate(); }
function remainingDays() { return Math.max(0, monthDays()-new Date().getDate()); }
function totals() { const items=state.movements.filter(inThisMonth); return { income:items.filter(x=>x.type==='income').reduce((a,x)=>a+x.ars,0), expense:items.filter(x=>x.type==='expense').reduce((a,x)=>a+x.ars,0), fixed:state.fixed.reduce((a,x)=>a+x.amount,0) }; }
function render() {
  const {income,expense,fixed}=totals(); const balance=state.initialBalance + state.movements.reduce((sum,m)=>sum+(m.type==='income'?m.ars:-m.ars),0);
  $('#current-balance').textContent=money(balance); $('#balance-detail').textContent=`Ingresos ${money(income)} · Gastos ${money(expense)}`;
  const d=new Date(), daysElapsed=Math.max(1,d.getDate()), daysLeft=remainingDays(), fixedRemaining=Math.max(0,fixed - state.movements.filter(inThisMonth).filter(x=>x.fixed).reduce((a,x)=>a+x.ars,0));
  const usable=Math.max(0,state.budget-expense-fixedRemaining); const weeks=Math.max(1,Math.ceil((daysLeft+1)/7));
  $('#weekly-available').textContent=money(usable/weeks); $('#weekly-detail').textContent=state.budget?`${money(usable)} para el resto del mes`:'Configurá tu presupuesto';
  const dailyRate=expense/daysElapsed; const projection=Math.max(0,state.budget-expense-fixedRemaining-(dailyRate*daysLeft));
  $('#month-projection').textContent=money(projection); $('#projection-detail').textContent=state.budget?`Si mantenés este ritmo de gasto`:'Sin presupuesto configurado';
  renderShortcuts(); renderMovements();
}
function renderShortcuts(){ const holder=$('#shortcuts'); holder.innerHTML=''; state.shortcuts.forEach((s,i)=>{ const b=$('#shortcut-template').content.firstElementChild.cloneNode(true); if(!s[1]) b.classList.add('empty'); b.querySelector('.shortcut-icon').textContent=s[0]||'+'; b.querySelector('.shortcut-name').textContent=s[1]||'Configurar'; b.querySelector('.shortcut-value').textContent=s[1]?(s[2]?money(s[2]):'Agregar'):'Atajo'; b.onclick=()=>s[1]&&openMovement('expense',s); holder.append(b); }); }
function renderMovements(){ const holder=$('#movements'); const items=state.movements.filter(inThisMonth).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5); holder.innerHTML=items.length?'':'<p class="empty-state">Todavía no registraste movimientos este mes.</p>'; items.forEach(m=>{ const el=document.createElement('article'); el.className='movement'; el.innerHTML=`<span class="movement-symbol">${m.type==='income'?'↗':'↘'}</span><div class="movement-main"><p class="movement-name">${escapeHtml(m.name)}${m.currency==='USD'?' · USD':''}</p><p class="movement-date">${formatDate(m.date)}</p></div><strong class="movement-value ${m.type}">${m.type==='income'?'+':'−'}${money(m.ars)}</strong>`; holder.append(el); }); }
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function openMovement(type='expense', shortcut=null){ selectedType=type; $('#movement-form').reset(); $('#movement-date').value=today(); $('#movement-name').value=shortcut?.[1]||''; $('#movement-amount').value=shortcut?.[2]||''; $('#movement-currency').value='ARS'; updateTypeUI(); updateConversionNote(); $('#movement-dialog').showModal(); setTimeout(()=>$('#movement-name').focus(),100); }
function updateTypeUI(){ document.querySelectorAll('#movement-type button').forEach(b=>b.classList.toggle('selected',b.dataset.type===selectedType)); }
function updateConversionNote(){ const isUsd=$('#movement-currency').value==='USD'; const amount=Number($('#movement-amount').value)||0; $('#conversion-note').textContent=isUsd ? `Se registrará como ${money(amount*(state.dollarRate||0))}${state.dollarRate?' según la última cotización.':' cuando se obtenga la cotización.'}` : ''; }
function fixedEditor(){ const holder=$('#fixed-editor'); holder.innerHTML=''; state.fixed.forEach((f,i)=>holder.insertAdjacentHTML('beforeend',`<div class="fixed-item"><input data-fixed-name="${i}" value="${escapeHtml(f.name)}" maxlength="30" placeholder="Ej. Gimnasio"><input data-fixed-amount="${i}" value="${f.amount||''}" type="number" min="0" placeholder="Monto"><button class="remove-fixed" type="button" data-remove-fixed="${i}" aria-label="Quitar gasto fijo">×</button></div>`)); }
async function getDollarRate(){ const type=$('#dollar-type').value; $('#dollar-rate').textContent='Actualizando cotización…'; try { const r=await fetch(`https://dolarapi.com/v1/dolares/${type}`); if(!r.ok) throw Error(); const data=await r.json(); state.dollarRate=data.venta; state.dollarType=type; save(); $('#dollar-rate').textContent=`Venta: ${money(data.venta)} por USD`; updateConversionNote(); } catch { $('#dollar-rate').textContent=state.dollarRate?`Última cotización: ${money(state.dollarRate)} por USD`:'No se pudo obtener la cotización. Revisá tu conexión.'; } }
$('#add-movement').onclick=()=>openMovement(); $('#settings-button').onclick=()=>{ $('#monthly-budget').value=state.budget||''; $('#initial-balance').value=state.initialBalance||''; $('#dollar-type').value=state.dollarType; $('#dollar-rate').textContent=state.dollarRate?`Última cotización: ${money(state.dollarRate)} por USD`:'Sin cotización guardada'; fixedEditor(); $('#settings-dialog').showModal(); };
$('#movement-type').onclick=e=>{ if(e.target.dataset.type){ selectedType=e.target.dataset.type; updateTypeUI(); } }; $('#movement-currency').onchange=updateConversionNote; $('#movement-amount').oninput=updateConversionNote;
$('#movement-form').addEventListener('submit',e=>{ if(e.submitter?.value==='cancel') return; const amount=Number($('#movement-amount').value); const currency=$('#movement-currency').value; if(currency==='USD'&&!state.dollarRate){ e.preventDefault(); getDollarRate(); return; } const name=$('#movement-name').value.trim(); const isFixed=selectedType==='expense'&&state.fixed.some(f=>f.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase()); state.movements.push({id:crypto.randomUUID(),name,amount,currency,ars:currency==='USD'?amount*state.dollarRate:amount,type:selectedType,fixed:isFixed,date:$('#movement-date').value}); save(); render(); });
$('#settings-form').addEventListener('submit',e=>{ if(e.submitter?.value==='cancel') return; state.budget=Number($('#monthly-budget').value)||0; state.initialBalance=Number($('#initial-balance').value)||0; state.dollarType=$('#dollar-type').value; state.fixed=[...$('#fixed-editor').querySelectorAll('[data-fixed-name]')].map(x=>({name:x.value.trim(),amount:Number($(`[data-fixed-amount="${x.dataset.fixedName}"]`).value)||0})).filter(x=>x.name&&x.amount>0); save(); render(); }); $('#add-fixed').onclick=()=>{state.fixed.push({name:'',amount:0});fixedEditor();}; $('#fixed-editor').onclick=e=>{const i=e.target.dataset.removeFixed;if(i!==undefined){state.fixed.splice(Number(i),1);fixedEditor();}}; $('#refresh-rate').onclick=getDollarRate; $('#dollar-type').onchange=getDollarRate;
$('#edit-shortcuts').onclick=()=>{ const h=$('#shortcuts-editor'); h.innerHTML=''; state.shortcuts.forEach((s,i)=>{ h.insertAdjacentHTML('beforeend',`<div class="shortcut-edit"><input class="emoji-input" data-i="${i}" data-f="emoji" value="${s[0]}" aria-label="Ícono ${i+1}"><label>Nombre<input data-i="${i}" data-f="name" value="${s[1]}" maxlength="18" placeholder="Ej. Merienda"></label><label>Monto<input data-i="${i}" data-f="amount" value="${s[2]||''}" type="number" min="0" placeholder="Opcional"></label></div>`); }); $('#shortcuts-dialog').showModal(); };
$('#shortcuts-form').addEventListener('submit',e=>{ if(e.submitter?.value==='cancel') return; const values=[...$('#shortcuts-editor').querySelectorAll('input')]; state.shortcuts=state.shortcuts.map((s,i)=>{const by=f=>values.find(v=>Number(v.dataset.i)===i&&v.dataset.f===f).value; return [by('emoji')||'•',by('name'),Number(by('amount'))||0];}); save(); render(); });
$('#view-all').onclick=()=>alert(state.movements.length ? state.movements.sort((a,b)=>b.date.localeCompare(a.date)).map(m=>`${formatDate(m.date)} · ${m.name} · ${m.type==='income'?'+':'-'}${money(m.ars)}`).join('\n') : 'No hay movimientos todavía.');
$('#month-label').textContent=new Date().toLocaleDateString('es-AR',{month:'long',year:'numeric'}); render(); if(!state.dollarRate) getDollarRate();
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');
